"""
pages/2_Analytics_Reports.py

Professional AI Generated Business Report Viewer

Displays:
- Executive Summary
- Technical ML Report
- Business Analysis
- Management Decisions
- Future Strategy
- Export Center
"""

import streamlit as st

from services.state import init_state
from services.report_service import (
    build_report,
    to_markdown,
    to_json_bytes,
    to_csv_bytes,
    to_pdf_bytes
)

from ui.theme import (
    apply_page_config,
    inject_global_css,
    hero,
    glass,
    kpi_card,
    render_sidebar
)


apply_page_config(
    "Analytics & Reports",
    icon="📈"
)

init_state()

inject_global_css()

render_sidebar(
    active="reports"
)


hero(
    "Analytics & Reports",
    "AI generated executive report combining machine learning analysis and business intelligence."
)


context = st.session_state.get(
    "pipeline_context"
)


if not context or not st.session_state.get("pipeline_ran"):

    glass(
        """
        No completed pipeline run yet.
        Go to <b>AI Workspace</b> and run the pipeline first.
        """
    )

    st.stop()



# ======================================================
# LOAD AI GENERATED REPORT
# ======================================================

# First priority:
# Report generated by InsightsReportAgent

report = context.get(
    "report"
)


# Fallback:
# Old technical report builder

if not report:

    report = build_report(
        context
    )



technical = report.get(
    "technical_report",
    {}
)


business = report.get(
    "business_report",
    {}
)



# ======================================================
# KPI HEADER
# ======================================================


overview = report.get(
    "dataset_overview",
    {}
)


model = report.get(
    "model_recommendation",
    {}
)



# fallback from pipeline context

if not overview:

    schema = context.get(
        "schema",
        {}
    )

    dataset = schema.get(
        "dataset",
        {}
    )


    overview = {

        "rows": dataset.get("rows"),

        "columns": dataset.get("columns")

    }



if not model:

    best_model = context.get(
        "best_model",
        {}
    )


    model = {

        "best_model": best_model.get(
            "model_name",
            "-"
        )

    }



model_info = technical.get(
    "model_information",
    {}
)



c1, c2, c3, c4 = st.columns(4)



with c1:

    st.markdown(
        kpi_card(
            "Dataset Rows",
            str(
                overview.get(
                    "rows",
                    "-"
                )
            )
        ),
        unsafe_allow_html=True
    )



with c2:

    st.markdown(
        kpi_card(
            "Columns",
            str(
                overview.get(
                    "columns",
                    "-"
                )
            )
        ),
        unsafe_allow_html=True
    )



with c3:

    st.markdown(
        kpi_card(
            "Model",
            str(
                model.get(
                    "best_model",
                    model_info.get(
                        "model_name",
                        "-"
                    )
                )
            )
        ),
        unsafe_allow_html=True
    )



with c4:

    st.markdown(
        kpi_card(
            "Target",
            str(
                model_info.get(
                    "target_variable",
                    "-"
                )
            )
        ),
        unsafe_allow_html=True
    )



st.markdown("---")



# ======================================================
# MAIN REPORT TABS
# ======================================================


tabs = st.tabs(
    [
        "Executive Summary",
        "Technical Report",
        "Business Analysis",
        "Management Decisions",
        "Execution Plan"
    ]
)



# ======================================================
# EXECUTIVE SUMMARY
# ======================================================


with tabs[0]:

    st.subheader(
        "Executive Summary"
    )


    glass(
        business.get(
            "executive_summary",
            "No executive summary available."
        )
    )


    st.markdown(
        "### Current Company Status"
    )


    glass(
        business.get(
            "current_company_status",
            "No company status available."
        )
    )



# ======================================================
# TECHNICAL REPORT
# ======================================================


with tabs[1]:


    st.subheader(
        "Machine Learning Evaluation"
    )


    model_info = technical.get(
        "model_information",
        {}
    )


    col1, col2, col3 = st.columns(3)



    with col1:

        st.metric(
            "Model",
            model_info.get(
                "model_name",
                "-"
            )
        )


    with col2:

        st.metric(
            "Problem Type",
            model_info.get(
                "problem_type",
                "-"
            )
        )


    with col3:

        st.metric(
            "Target",
            model_info.get(
                "target_variable",
                "-"
            )
        )



    st.markdown(
        "### Performance Summary"
    )


    glass(
        technical.get(
            "model_performance_summary",
            ""
        )
    )



    with st.expander(
        "Evaluation Metrics"
    ):

        st.json(
            technical.get(
                "evaluation_metrics",
                {}
            )
        )



    with st.expander(
        "Technical Findings"
    ):

        for item in technical.get(
            "technical_findings",
            []
        ):

            st.write(
                "•",
                item
            )



    with st.expander(
        "Technical Risks"
    ):

        for item in technical.get(
            "technical_risks",
            []
        ):

            st.warning(
                item
            )



    with st.expander(
        "Technical Improvements"
    ):

        for item in technical.get(
            "technical_improvements",
            []
        ):

            st.write(
                "•",
                item
            )



# ======================================================
# BUSINESS ANALYSIS
# ======================================================


with tabs[2]:


    st.subheader(
        "Business Intelligence Analysis"
    )


    sections = [

        (
            "Business KPI Analysis",
            business.get(
                "business_kpi_analysis",
                {}
            )
        ),


        (
            "Sales & Profit Drivers",
            business.get(
                "sales_and_profit_drivers",
                []
            )
        ),


        (
            "Product Analysis",
            business.get(
                "product_category_analysis",
                {}
            )
        ),


        (
            "Regional Analysis",
            business.get(
                "regional_analysis",
                {}
            )
        ),


        (
            "Discount & Pricing Analysis",
            business.get(
                "discount_and_pricing_analysis",
                {}
            )
        ),


        (
            "Customer Analysis",
            business.get(
                "customer_analysis",
                {}
            )
        )

    ]



    for title, data in sections:

        with st.expander(
            title
        ):

            st.json(
                data
            )



    st.markdown(
        "### Business Risks"
    )


    for risk in business.get(
        "business_risks",
        []
    ):

        st.error(
            risk
        )



    st.markdown(
        "### Business Opportunities"
    )


    for item in business.get(
        "business_opportunities",
        []
    ):

        st.success(
            item
        )



# ======================================================
# MANAGEMENT DECISIONS
# ======================================================


with tabs[3]:


    st.subheader(
        "Executive Decisions"
    )


    for decision in business.get(
        "management_decisions",
        []
    ):

        st.markdown(
            "### Decision"
        )

        st.write(
            decision.get(
                "decision",
                ""
            )
        )


        st.markdown(
            "**Reason:**"
        )

        st.write(
            decision.get(
                "reason",
                ""
            )
        )


        st.markdown(
            "**Expected Business Value:**"
        )


        st.write(
            decision.get(
                "expected_business_value",
                ""
            )
        )


        st.divider()



    st.markdown(
        "### Future Strategy"
    )


    for item in business.get(
        "future_strategy",
        []
    ):

        st.write(
            "•",
            item
        )



    st.markdown(
        "### Final Executive Conclusion"
    )


    glass(
        business.get(
            "final_executive_conclusion",
            ""
        )
    )



# ======================================================
# EXECUTION PLAN
# ======================================================


with tabs[4]:

    st.json(
        report.get(
            "execution_plan",
            context.get(
                "plan",
                {}
            )
        )
    )



# ======================================================
# EXPORT CENTER
# ======================================================


st.markdown("---")


st.subheader(
    "Download Center"
)


d1, d2, d3, d4 = st.columns(4)



with d1:

    st.download_button(
        "Download Markdown",
        data=to_markdown(report),
        file_name="business_ai_report.md",
        mime="text/markdown",
        use_container_width=True
    )



with d2:

    st.download_button(
        "Download JSON",
        data=to_json_bytes(report),
        file_name="business_ai_report.json",
        mime="application/json",
        use_container_width=True
    )



with d3:

    st.download_button(
        "Download CSV",
        data=to_csv_bytes(report),
        file_name="model_results.csv",
        mime="text/csv",
        use_container_width=True
    )



with d4:

    pdf = to_pdf_bytes(
        report
    )


    if pdf:

        st.download_button(
            "Download PDF",
            data=pdf,
            file_name="business_ai_report.pdf",
            mime="application/pdf",
            use_container_width=True
        )

    else:

        st.button(
            "PDF unavailable",
            disabled=True,
            use_container_width=True
        )